// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy4b_CN_gqrC3Bx3Qun1fD8_e7HxA4hoc',
    appId: '1:411154917949:web:8b0491ed0e1237edab9854',
    messagingSenderId: '411154917949',
    projectId: 'graduate-student-app',
    authDomain: 'graduate-student-app.firebaseapp.com',
    storageBucket: 'graduate-student-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhLxc3iF_C4k7OI9bHSY7COwVqhK5w140',
    appId: '1:411154917949:android:00597cca77bbcc61ab9854',
    messagingSenderId: '411154917949',
    projectId: 'graduate-student-app',
    storageBucket: 'graduate-student-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArAsm9SC0AbkbLGfxCiePTgIEXH0_rxEc',
    appId: '1:411154917949:ios:c8489385dba42c34ab9854',
    messagingSenderId: '411154917949',
    projectId: 'graduate-student-app',
    storageBucket: 'graduate-student-app.firebasestorage.app',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArAsm9SC0AbkbLGfxCiePTgIEXH0_rxEc',
    appId: '1:411154917949:ios:c8489385dba42c34ab9854',
    messagingSenderId: '411154917949',
    projectId: 'graduate-student-app',
    storageBucket: 'graduate-student-app.firebasestorage.app',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy4b_CN_gqrC3Bx3Qun1fD8_e7HxA4hoc',
    appId: '1:411154917949:web:9242e34b51b052abab9854',
    messagingSenderId: '411154917949',
    projectId: 'graduate-student-app',
    authDomain: 'graduate-student-app.firebaseapp.com',
    storageBucket: 'graduate-student-app.firebasestorage.app',
  );
}
